# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tableViewTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tableViewTest
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxDataSources'
end
