use_frameworks!
platform :ios, '12.0'

target 'QuickTodo' do
  # core RxSwift
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxDataSources', '~> 3.1'

  # Community projects
  pod 'Action', '~> 3.9'
  pod 'NSObject+Rx', '~> 4.4'
  
  # Realm database
  pod 'RealmSwift', '~> 3.13'
  pod 'RxRealm', '~> 0.7.6'
end
